### ISSUE TITLE
MQTT Connect err:2

### ISSUE THREAD

**Issue by AkinoMaple** [xinyu198736/arduino-aliyun-iot-sdk#2]
设备:ESP8266
我尝试连接阿里云 返回错误 MQTT Connect err:2
REGION_ID被设置为cn-shanghai，其余的信息均准确无误，网络连接正常……
由于我对C++并不熟悉，无法进一步查明原因，望dalao相助

**Comment by kexuebiao** [comment]
https://www.21ic.com/article/870139.html

**Comment by zlflying** [comment]
1、这个错误出现在mqtt客户端与阿里云物联网平台加密连接的语句上，使用的ESP8266作为一个mqtt客户端，客户端按照mqtt的协议，将设备的三元组信息加密，然后通过网络连接到阿里云物联网平台。

2、返回的错误代码为2，通过查看PubSubClient.h文件得到错位代码2为MQTT_CONNECT_BAD_CLIENT_ID

3、找到PubSubClient.h头文件，打开找到MQTT_MAX_PACKET_SIZE，将256修改为1024，再找到MQTT_KEEPALIVE，将15修改为40后编译烧录后即可。
