### ISSUE TITLE
Request to add Unique-certificate-per-product authentication

### ISSUE THREAD

**Issue by TechMaxed** [xinyu198736/arduino-aliyun-iot-sdk#4]
I wanted to install the same firmware for many of my devices so I found this: [https://www.alibabacloud.com/help/doc-detail/74006.htm?spm=a2c63.p38356.b99.31.122433da0kZ3K9](url) I looked through the source code and couldn't find how I can connect my nodemcu without using the device secret. I also tried editing your code and it still doesn't work. Would you be able to implement the suggestion? Thanks. I would love to help you if you need it.

**Comment by xinyu198736** [comment]
you must need device secret to connect device

**Comment by TechMaxed** [comment]
> 
> 
> you must need device secret to connect device

@xinyu198736 Hello, thanks for replying. There is another method to connect a device to aliyun iot. All you need is to provide a ProductKey and ProductSecret. This is what it says from the link above: "Using unique-certificate-per-product authentication method requires that devices of a product have been installed with a same firmware in which a product certificate (ProductKey and ProductSecret) has been installed. When a device initiates an activation request, IoT Platform authenticates the product certificate of the device. After the authentication is passed, IoT Platform assigns the corresponding DeviceSecret to the device." It also said that the unique-certificate-per-product method is used to obtain the DeviceSecret of devices from IoT Platform. The DeviceSecret is only issued once. The device stores the DeviceSecret for future use. For some reason my links aren't working so here is the pdf file of the documentation. The docs is in 4.3 Unique-certificate-per-product authentication
[Device_Access_intl_en-US.pdf](https://github.com/xinyu198736/arduino-aliyun-iot-sdk/files/4051872/Device_Access_intl_en-US.pdf)

**Comment by xinyu198736** [comment]
After carefully reading your question, finally know what you mean, you made of the document, about a client SDK, built-in programs through a network request to exchange deviceSecret of. If you use nodemcu, you need to implement this logic in the SDK yourself. When I use it myself, I make a management service myself, and then all the devices are programmed with the same software. Every time the device initializes, I go to an http service request deviceSecret, and then pass in this SDK to initialize the IoT connection.

**Comment by TechMaxed** [comment]
@xinyu198736 Thank you for replying. I get this now. Please remove this post since the problem is solved. Thank you so much.
