### ISSUE TITLE
找不到#include <SHA256.h>头文件

### ISSUE THREAD

**Issue by daniao2017** [xinyu198736/arduino-aliyun-iot-sdk#5]
尝试了很多种办法用esp8266连接阿里云，

1. 参考[NodeMCU(ESP8266)接入阿里云物联网平台](https://developer.aliyun.com/article/740235?spm=a2c6h.12873581.0.0.6226319aDPXirZ)这篇博客，直接自己贴上mqtt的password，先是报错error=-1的错，**没有修改#include <PubSubClient.h>的头文件**修改之后，参考这篇博客[基于开源MQTT自主接入阿里云IoT平台](https://www.yuque.com/cloud-dev/iot-tech/mebm5g)，修改相应密码报，errr=4的错误，用户或密码格式数据无效，不懂了？？？

2. 参考这篇博客，直接代码生产密码，[ESP8266(arduino方式)快速连接阿里云物联网平台](https://blog.csdn.net/ziqi5543/article/details/88710552)，和博主的方法大致是一样的，但是运行到最后也是缺少**include<SHA256.h>头文件**
博主能解答一下吗，谢谢！

**Comment by xinyu198736** [comment]
网上的很多文章考虑的问题不够细，会出现各种错误。
SHA256.h 是需要自己引入的，或者去网上找到源码放到项目里

**Comment by kartwu** [comment]
我试了好使的解决方法：
在Arduino库管理中，下载库<arduinolibs-master>。
解压后把<arduinolibs-master.zip\arduinolibs-master\libraries\Crypto>
复制到<Arduino\libraries>目录下。
目的是<Crypto>其中有包含SHA256的CPP和H文件。

然后示例程序就调通了。
这个SDK感觉很方便用，非常感谢！

**Comment by yuiopt** [comment]
直接在ArduinoIDE里面的库管理里面搜索arduinolibs，安装Crypto库

**Comment by daniao2017** [comment]
> 
> 
> 直接在ArduinoIDE里面的库管理里面搜索arduinolibs，安装Crypto库

好的，感谢回复，已经爬过了这个坑。期待博主在下一次版本的迭代更新中把这个库给整合到项目里面去呗

**Comment by daniao2017** [comment]
感谢各位的热心解答，已经解决了没有`#include <SHA256.h>`库的问题，具体可以参考上面大佬的回复。
